const FETCH_POSTS = "FETCH_POSTS";
const SETUP_POST = "SETUP_POST";
const ADD_POST = "ADD_POST";
const LOADING_DATA = "LOADIN_DATA";
const ERR_MESSAGE = "ERR_MESSAGE";

export { FETCH_POSTS, ADD_POST, LOADING_DATA, ERR_MESSAGE, SETUP_POST };
